apiVersion: v1
kind: Template
labels:
  template: wiremock
  module: traceability
metadata:
  annotations:
    description: |
      Template to deploy Wiremock
    iconClass: icon-openjdk
    tags: runtime,instant-app,javase,openjdk
    openshift.io/provider-display-name: ALM Multicloud.
  name: wiremock
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app_name: ${APP_NAME}
      module: traceability
      template: wiremock
    name: ${APP_NAME}
  spec:
    ports:
    - name: 8080-tcp
      nodePort: 0
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app_name: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app_name: ${APP_NAME}
      module: traceability
      template: wiremock
    name: ${APP_NAME}
  spec:
    tls:
      termination: edge
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${APP_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app_name: ${APP_NAME}
      module: traceability
      template: wiremock
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app_name: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      rollingParams:
        intervalSeconds: 1
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app_name: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
          module: traceability
          template: wiremock
      spec:
        containers:
        - env:
          - name: APP_NAME
            value: ${APP_NAME}
          image: ${TAGGED_IMAGE}
          imagePullPolicy: Always
          name: ${APP_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
  status: {}
parameters:
- description: Application name
  displayName: Application Name
  name: APP_NAME
  required: true
- description: Container Image
  displayName: TAGGED_IMAGE
  name: TAGGED_IMAGE
  required: true